### ISSUE TITLE
Learn about OLED screen

### ISSUE THREAD

**Issue by amolakplaha** [f-0-o/Smart-Trash-Can#29]
Write report as you are learning

**Comment by ffund** [comment]
@amolakplaha spoke to Shahzeb to determine which datasheet to use, because there was some confusion on this matter.

**Comment by amolakplaha** [comment]
https://www.velleman.eu/downloads/29/infosheets/sh1106_datasheet.pdf

**Comment by amolakplaha** [comment]
This issue is linked to issue #33. Should I move this issue to "done" if issue #33 is moved to "done" @ffund?

**Comment by ffund** [comment]
@amolakplaha It doesn't look like you did anything on this issue - you documented everything you did with the OLED on #33 

so you might consider deleting this issue, and editing the title/description of #33 to reflect that it's about more than "checking if the part is alive".
