### ISSUE TITLE
Learn about OLED

### ISSUE THREAD

**Issue by f-0-o** [f-0-o/Smart-Trash-Can#33]
Connect it to pi
Setup initialization function and check signals with Analog Discovery 2. 
Check for output voltage. 
Use python library to draw basic display. 
In this issue :
describe how to connect it and show schematic/breadboard photo. describe how to connect to AD2 for scope measurements and show measurements for different distances. Show relevant portion of sensor datasheet that describes how output should change with respect to distance.

**Comment by amolakplaha** [comment]
Do not need to set up with Analog Discovery 2. 
Set up OLED and got back proper results. 
I will continue working on displaying images, t
<img width="381" alt="Screen Shot 2022-02-26 at 6 20 41 PM" src="https://user-images.githubusercontent.com/98905458/155864977-3c00dc9d-314b-4b77-81bc-e595c48a0847.png">
<img width="794" alt="Screen Shot 2022-02-26 at 6 07 28 PM" src="https://user-images.githubusercontent.com/98905458/155864978-5d5add81-4cb9-4071-bddf-647e6f61d94f.png">
<img width="794" alt="Screen Shot 2022-02-26 at 6 06 21 PM" src="https://user-images.githubusercontent.com/98905458/155864979-9f399d92-2e67-4c3c-bea8-1ecd26d6f155.png">
<img width="604" alt="Screen Shot 2022-02-26 at 6 01 56 PM" src="https://user-images.githubusercontent.com/98905458/155864980-d31a50a0-d371-4334-803c-7795789ea6dd.png">
exts, and plots.

**Comment by amolakplaha** [comment]
Took about 2.5 hours to check liveness and write many versions of code.

**Comment by amolakplaha** [comment]
The SSD1106 needs a digital communication bus to connect to the Raspberry Pi, specifically the I2C communication bus. The ssd1106 can read and display memory through an I2C data bus. In the datasheet, page 8 states the protocols of the I2C. It says that the “two 7-bit slave addresses (0111100 and 0111101) are reserved.
Figure 1 shows the I2C protocol. The master-slave protocol sends the slave address and slave device to the data line and address and gets data and sends the acknowledgment. Then data is transmitted between the master device and slave after each message. The frame presentation starts from the start condition and ends at the end condition and then both devices are disconnected.
Figures 2 and 3 show all the commands. These are the commands based on the OLED display unit which has different registers. I2C protocol frames the data transmission, and each command controls the OLED display. There are different data patterns in form of bits that control the functionality of the display.


<img width="494" alt="Screen Shot 2022-02-28 at 4 34 01 PM" src="https://user-images.githubusercontent.com/98905458/156424972-2f977603-fadc-4758-bf38-8b0b24847ca6.png">

**Comment by amolakplaha** [comment]
<img width="496" alt="Screen Shot 2022-02-28 at 4 33 49 PM" src="https://user-images.githubusercontent.com/98905458/156425024-5893f5a2-1e83-4675-9d14-fc6f61fc5224.png">

**Comment by amolakplaha** [comment]
<img width="503" alt="Screen Shot 2022-02-28 at 4 33 10 PM" src="https://user-images.githubusercontent.com/98905458/156425058-8aac5d6b-c463-4172-9658-98902a9b08f7.png">

**Comment by amolakplaha** [comment]
The images from checking the liveness are shown here.
<img width="343" alt="Screen Shot 2022-03-05 at 3 02 00 PM" src="https://user-images.githubusercontent.com/98905458/156898363-1fd3666c-8a97-472b-bb95-3e24ab35ce66.png">
<img width="358" alt="Screen Shot 2022-03-05 at 3 02 06 PM" src="https://user-images.githubusercontent.com/98905458/156898364-e4de0340-52d0-4fde-8af3-96b0a7b45e1e.png">
<img width="248" alt="Screen Shot 2022-03-05 at 3 02 12 PM" src="https://user-images.githubusercontent.com/98905458/156898365-982fd754-5adb-4dd4-bdf1-d5c5ca00574b.png">
<img width="250" alt="Screen Shot 2022-03-05 at 3 02 16 PM" src="https://user-images.githubusercontent.com/98905458/156898366-aec861af-df12-456f-a4a5-5e5bb8d60704.png">
<img width="419" alt="Screen Shot 2022-03-05 at 3 02 27 PM" src="https://user-images.githubusercontent.com/98905458/156898367-629d7ace-95f3-45d5-b612-101089565b99.png">

**Comment by amolakplaha** [comment]
Connecting to 12C and checking part liveness by the following procedure:

To enable the I2C on the Raspberry Pi, you need to run:
sudo raspi-config
There will be several options shown on the screen. Using the tab and arrow keys, choose Interfacing Options, I2C, “Yes”, “OK”, and “Finish.” To check that is it enabled, run
lsmod | grep i2c
To check the outputs of the pins, run
gpio readall
This will show the two I2C pins in “ALT” mode. 
Next, the software tools and libraries need to be installed to work alongside with I2C. To do this, run:
sudo apt update
sudo apt upgrade
sudo -H pip3 install luma.oled
sudo -H pip3 install --upgrade luma.oled sudo apt-get install python3-smbus
This will take time, but that is OK. Next, the OLED will be connected to a breadboard. The following ports will be connected to the Pi:
GND to GND
VCC/VDD to 3.3V
SCL/SCK to GPIO3 (I2C1 SCL) on the Pi SDA to GPIO2 (I2C1 SDA) on the Pi

To address the I2C device, we run the following command. The output should look like the one shown in respective screenshot. This shows that your part is connected and working.
i2cdetect -y 1
