### ISSUE TITLE
Set up Pi

### ISSUE THREAD

**Issue by f-0-o** [f-0-o/Smart-Trash-Can#38]
Amolak needs to connect new phone to Pi.

**Comment by amolakplaha** [comment]
I tried flashing the SD card to connect my wifi to it, however, it was just not identifying it. I also went to go buy an SD card reader to do this. Followed many videos however, could not figure it out. I will try to figure it out again tomorrow. Time spent today: 2.5 hours

**Comment by amolakplaha** [comment]
Fixed problem. New ping for iphone is at 172.20.10.4
