### ISSUE TITLE
Check part "liveness" for distance sensor

### ISSUE THREAD

**Issue by amolakplaha** [f-0-o/Smart-Trash-Can#4]
* Connect to power
* Measure output voltage on the output pin (e.g. with Analog Discovery 2 scope) - refer to datasheet to see if it should increase or decrease with distance

In this issue: describe how to connect it and show schematic/breadboard photo. describe how to connect to AD2 for scope measurements and show measurements for different distances. Show relevant portion of sensor datasheet that describes how output should change with respect to distance.

**Comment by amolakplaha** [comment]
Incorrectly made issues. Disregard the description above. 
In this part, we must check the "liveness" of the part using photo/schematic, code and/or instructions, expected result of the "liveness" test.

**Comment by amolakplaha** [comment]
See whiteboard from 2/27

**Comment by f-0-o** [comment]
I think either my part is dead or the connection is not proper. Gonna have to recheck it ASAP. 

![IMG_8669](https://user-images.githubusercontent.com/98905164/155257446-a5acf5ef-30ad-4700-916d-ad1e24484221.jpeg)

![IMG_8670](https://user-images.githubusercontent.com/98905164/155257430-221160a8-061f-404f-9156-5a8ed2819a1a.jpeg)

**Comment by f-0-o** [comment]
The issue has been resolved. IR distance sensor is live. Getting expected output as described in the datasheet. I'll update the post with a video tutorial to check the liveness.
![IMG_8677](https://user-images.githubusercontent.com/98905164/155383298-c1988909-3681-4ced-aa76-7d691f2e0554.jpeg)
