### ISSUE TITLE
Create personas

### ISSUE THREAD

**Issue by amolakplaha** [f-0-o/Smart-Trash-Can#47]
*At least N+1 for an N-sized team.

**Comment by amolakplaha** [comment]
My research began where I searched up reasons as to why people don’t like taking out the trash. Theses include:
- It smells
- The liquid In the trash makes me more unlikely to take it out. 

The Strategist, rated 5 of the very best kitchen trash cans. The features they based it on include:
- Material
- Capacity
- Compartments
- Closures
- Price

The experts to conduct the research for this list include interior designers, organizers, architects, etc. 

https://medium.com/ignation/your-guide-to-successful-persona-building-f3dae3f4762d

**Comment by fahimbyte** [comment]
Persona 1:
William
High Schooler

About William:
- Loves to play video games
- At home after school if there is nothing to do 
- Usually plays sports after school 
- Doing schoolwork is the last priority 
- Never bother taking out the trash cause it is not fun.
- Loves being the center of attention and always assumes he's right 

Key goals and needs:

- Stay on top of school work.
- Doesn't want to get grounded by his mom for not doing work 
- Wants amazing grades without putting in any effort
- Be popular 
- To excell in the sports he participates in

**Comment by amolakplaha** [comment]
Persona 2: 

Katherine
The Busy Mom

About Katherine: 
- Age: 34 
- Has kids; 7-11-year-olds
- Works a 9 am - 5 pm job every day 
- Preps meal for the week on Sunday with her husband
- Neat freak who needs the house to be mostly organized and cleaned the majority of the time 
- Get frustrated when no one cleans up after themselves and doesn't help out

Key goals and needs: 
- Needs kids and husband to do their share of chores
- Stay on top of work 
- Come home on time
- Wants kids to excel in school and know when to help out at home without asking
- Wants a stress-free dynamics at home with family.
- Wants to raise her children to be capable of becoming independent adults one day so instilling chores and other things from an early age will get them ready to face the world themselves 
- Wants her kids to respect her for the work she does both in an out of the house and understand how difficult it can be 
- Wants the family to bond over even the smallest things to make memories to last a lifetime

**Comment by fahimbyte** [comment]
Persona 3:

Daniel
Food Lover, Room Mate

About Daniel:

- 23, bachelor, lives in a shared apartment
- Works in an s technology firm.
- Apartment has the bare minimum. 
- Doesn't like children, responsibilities, and cooking.
- Likes to earn money, spend it, and party.
- Likes spending time with his girlfriend inside or outside his apartment
- Uses technology as an escape from stress 


Key goals and needs:
- Tolerable environment to complete basic needs.
- Wants to own his own company by 35.
- Watching his friends succeed motivates him. 
- Essentially likes to keep life simple and fun
